// <auto-generated />
using DevInCar.GraphQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api_graphql.Migrations
{
    [DbContext(typeof(DevContext))]
    partial class DevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevInCar.GraphQL.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "V4eY8fFKDg",
                            UserName = "User1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "GJARed1TU0",
                            UserName = "User2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "NSYfC9yLzt",
                            UserName = "User3"
                        });
                });

            modelBuilder.Entity("DevInCar.GraphQL.Models.Veiculo", b =>
                {
                    b.Property<int>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeiculoId"), 1L, 1);

                    b.Property<int>("CapacidaDeCarga")
                        .HasColumnType("int");

                    b.Property<string>("Chassi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Combustivel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataFabricacao")
                        .HasColumnType("int");

                    b.Property<string>("NomeModelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portas")
                        .HasColumnType("int");

                    b.Property<double>("Potencia")
                        .HasColumnType("float");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rodas")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("VeiculoId");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            VeiculoId = 1,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSIGHJOLNQSED4",
                            Combustivel = "Gasolina",
                            Cor = "Cinza",
                            DataFabricacao = 2019,
                            NomeModelo = "Fiat Uno",
                            Placa = "CAR3XFV",
                            Portas = 4,
                            Potencia = 75.0,
                            Preco = 43.807m,
                            Rodas = 0,
                            Status = 0,
                            Tipo = 2
                        },
                        new
                        {
                            VeiculoId = 2,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSIKSRAL4DOKCK",
                            Combustivel = "Flex",
                            Cor = "Preto",
                            DataFabricacao = 2018,
                            NomeModelo = "VW GOL",
                            Placa = "CAR3FFV",
                            Portas = 4,
                            Potencia = 82.0,
                            Preco = 47.507m,
                            Rodas = 0,
                            Status = 0,
                            Tipo = 2
                        },
                        new
                        {
                            VeiculoId = 3,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSIEFT90SL35HL",
                            Combustivel = "Gasolina",
                            Cor = "Branco",
                            DataFabricacao = 2017,
                            NomeModelo = "Renault Duster",
                            Placa = "CAR3XFV",
                            Portas = 4,
                            Potencia = 118.0,
                            Preco = 67.907m,
                            Rodas = 0,
                            Status = 1,
                            Tipo = 2
                        },
                        new
                        {
                            VeiculoId = 4,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSI12454T4T456",
                            Cor = "Cinza",
                            DataFabricacao = 2022,
                            NomeModelo = "CG 160 Titan",
                            Placa = "PLC1234",
                            Portas = 0,
                            Potencia = 15.1,
                            Preco = 14.620m,
                            Rodas = 2,
                            Status = 0,
                            Tipo = 3
                        },
                        new
                        {
                            VeiculoId = 5,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSI123DFGEVGBU",
                            Cor = "Azul",
                            DataFabricacao = 2017,
                            NomeModelo = "CG 160 Fan",
                            Placa = "BRA2S5D",
                            Portas = 0,
                            Potencia = 15.1,
                            Preco = 13.480m,
                            Rodas = 2,
                            Status = 0,
                            Tipo = 3
                        },
                        new
                        {
                            VeiculoId = 6,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSIQER234GYHJC",
                            Cor = "Branco",
                            DataFabricacao = 2022,
                            NomeModelo = "CG 160 Cargo",
                            Placa = "CBA3S5K",
                            Portas = 0,
                            Potencia = 15.1,
                            Preco = 13.650m,
                            Rodas = 2,
                            Status = 1,
                            Tipo = 3
                        },
                        new
                        {
                            VeiculoId = 7,
                            CapacidaDeCarga = 1820,
                            Chassi = "CHASSIFA3DVFOLM1D7",
                            Combustivel = "Diesel",
                            Cor = "Branco",
                            DataFabricacao = 2021,
                            NomeModelo = "Fiat Toro",
                            Placa = "P1CKUP7",
                            Portas = 4,
                            Potencia = 139.0,
                            Preco = 103.907m,
                            Rodas = 0,
                            Status = 0,
                            Tipo = 0
                        },
                        new
                        {
                            VeiculoId = 8,
                            CapacidaDeCarga = 1920,
                            Chassi = "CHASSIYUI789O50HL",
                            Combustivel = "Gasolina",
                            Cor = "Prata",
                            DataFabricacao = 2021,
                            NomeModelo = "Toyota Hilux",
                            Placa = "TYT678X",
                            Portas = 4,
                            Potencia = 204.0,
                            Preco = 238.907m,
                            Rodas = 0,
                            Status = 0,
                            Tipo = 0
                        },
                        new
                        {
                            VeiculoId = 9,
                            CapacidaDeCarga = 1850,
                            Chassi = "CHASSL3ADFTTH7OGH",
                            Combustivel = "Diesel",
                            Cor = "Prata",
                            DataFabricacao = 2021,
                            NomeModelo = "Chevrolet s10",
                            Placa = "CHVR3FL",
                            Portas = 4,
                            Potencia = 206.0,
                            Preco = 113.907m,
                            Rodas = 0,
                            Status = 1,
                            Tipo = 0
                        },
                        new
                        {
                            VeiculoId = 10,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSI123AZXSDCFE4",
                            Cor = "Azul",
                            DataFabricacao = 2021,
                            NomeModelo = "Tricity 300",
                            Placa = "TRI1237",
                            Portas = 0,
                            Potencia = 20.600000000000001,
                            Preco = 48.650m,
                            Rodas = 3,
                            Status = 0,
                            Tipo = 1
                        },
                        new
                        {
                            VeiculoId = 11,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSI678GTUHJKXOL",
                            Cor = "Branco",
                            DataFabricacao = 2022,
                            NomeModelo = "Tricity 125",
                            Placa = "CITY123",
                            Portas = 0,
                            Potencia = 9.0,
                            Preco = 24.009m,
                            Rodas = 3,
                            Status = 0,
                            Tipo = 1
                        },
                        new
                        {
                            VeiculoId = 12,
                            CapacidaDeCarga = 0,
                            Chassi = "CHASSIRTYMKO5B8M0Z",
                            Cor = "Branco",
                            DataFabricacao = 2021,
                            NomeModelo = "Tricity 125",
                            Placa = "BA12K45",
                            Portas = 0,
                            Potencia = 20.600000000000001,
                            Preco = 58.805m,
                            Rodas = 3,
                            Status = 1,
                            Tipo = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
